version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - f1-docker-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - f1-docker-network

networks:
  f1-docker-network:
    driver: bridge
